#!/usr/bin/env python3
"""check_go_schema.py — validate that GO verification-report events carry real evidence.

R-GATE-EVIDENCE (ADR-003): a `verification-report` mailbox event whose verdict is GO
MUST contain all three of:
  1. an explicit verdict token (`VERDICT: GO`),
  2. a `## Evidence` section with BOTH a command line (`$ <cmd>`) AND its output
     (`→ <result>`),
  3. a commit SHA (from the auto H1 ``commit `<sha>` `` pattern) OR a `logs/` artifact
     reference anywhere in the body.

Sub-rule: a GO whose evidence references `wave_gate_check` and contains NO pytest /
regression-pin (`--runxfail`) output → FAIL.  wave_gate_check reads an inventory
string; it does not execute tests, so it is not GO-grade evidence.

NITS / FAIL verdicts make no ship-claim → NOT gated (mirrors check_no_ceremony R6,
which gates only the `pass` verdict).

Only the v6.0 `VERDICT: GO` shape is gated (canonical, per
`.claude/skills/seat-operator/verification-report-format.md`).  The grandfathered YAML
`**Status:** ✅ clean` form is NOT handled here — see the report for rationale.

Usage:  .venv/bin/python scripts/check_go_schema.py [<dir>]
        <dir> defaults to coordination/mailbox/sent/
        Scans for *-verification-report.md files.

Exit codes:
    0 — clean (no GO reports, or all GO reports carry complete evidence)
    1 — at least one GO report is missing a required field (named in output)
"""
from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Default scan directory (overridable by CLI argument for tests).
DEFAULT_MAILBOX = ROOT / "coordination" / "mailbox" / "sent"

# --- Patterns (v6.0 verification-report-format.md) --------------------------

# VERDICT token in the body. Broadened to gate decorated/suffixed GO lines
# (`**VERDICT: GO**`, `VERDICT: GO (pending)`) so an off-form GO cannot silently
# fail-open past all evidence checks. The `\bGO\b` word boundary still EXCLUDES
# `VERDICT: NITS`, `VERDICT: FAIL`, and `VERDICT: GONZO` (GONZO is rejected because
# the boundary requires a non-word char after `GO`).
_VERDICT_GO_RE = re.compile(r"^\s*\**\s*VERDICT:\s*GO\b", re.MULTILINE)

# ## Evidence section (must be present).
_EVIDENCE_SECTION_RE = re.compile(r"^##\s+Evidence\b", re.MULTILINE)

# A `$ cmd` line inside ## Evidence.
_CMD_LINE_RE = re.compile(r"^\s*\$\s+\S", re.MULTILINE)

# A `→ out` line inside ## Evidence.
_OUT_LINE_RE = re.compile(r"^→\s+\S", re.MULTILINE)

# Commit SHA: backtick-quoted SHA in H1 (auto-generated by send-event).
# Pattern: commit `<sha>` where sha is a hex string of 7–40 chars.
_SHA_H1_RE = re.compile(r"commit\s+`[0-9a-f]{7,40}`", re.IGNORECASE)

# Fallback: any `logs/` artifact reference anywhere in the body.
_LOGS_REF_RE = re.compile(r"\blogs/\S+")

# Sub-rule: wave_gate_check cited in evidence but no REAL pytest execution signal.
# The bare prose word "pytest" (e.g. "I did not run pytest") must NOT count — only a
# genuine execution marker does: a `--runxfail` token inside a `$ ` command line, OR a
# pytest RESULT marker (`\d+ passed/failed/xpassed/xfailed/error`).
_WAVE_GATE_RE = re.compile(r"\bwave_gate_check\b")
_PYTEST_CMD_RUNXFAIL_RE = re.compile(r"^\s*\$\s+.*--runxfail\b", re.MULTILINE)
_PYTEST_RESULT_RE = re.compile(r"\b\d+\s+(passed|failed|xpassed|xfailed|error)\b")


def _has_real_pytest_evidence(text: str) -> bool:
    """True iff `text` contains a real pytest execution signal (not the bare word)."""
    return bool(_PYTEST_CMD_RUNXFAIL_RE.search(text) or _PYTEST_RESULT_RE.search(text))


def _extract_evidence_block(body: str) -> str:
    """Return the text from `## Evidence` through the next `##` section (or EOF)."""
    m = _EVIDENCE_SECTION_RE.search(body)
    if not m:
        return ""
    start = m.start()
    # Find the next ## heading after the Evidence section.
    next_section = re.search(r"^##\s+\S", body[m.end():], re.MULTILINE)
    if next_section:
        return body[start : m.end() + next_section.start()]
    return body[start:]


def go_report_violations(
    named_reports: list[tuple[str, str]],
) -> list[str]:
    """Return a list of violation strings for GO reports that are missing required fields.

    Pure function over (name, body) pairs — no filesystem I/O, so the test does not
    need a real mailbox directory.

    Only `VERDICT: GO` events are gated; NITS / FAIL make no ship-claim.
    Each violation string names the offending file and the missing field.
    """
    violations: list[str] = []
    for name, body in named_reports:
        if not _VERDICT_GO_RE.search(body):
            # Not a GO report — NITS/FAIL are not gated.
            continue

        missing: list[str] = []

        # Check ## Evidence section exists.
        evidence_block = _extract_evidence_block(body)
        if not evidence_block:
            missing.append("missing `## Evidence` section")
        else:
            # Both `$ cmd` and `→ output` must appear inside the Evidence block.
            if not _CMD_LINE_RE.search(evidence_block):
                missing.append("missing `$ <cmd>` command line in ## Evidence")
            if not _OUT_LINE_RE.search(evidence_block):
                missing.append("missing `→ <result>` output line in ## Evidence")

            # Sub-rule R-GATE-EVIDENCE: wave_gate_check without REAL pytest execution
            # evidence is ceremony. The bare prose word "pytest" does not count.
            if _WAVE_GATE_RE.search(evidence_block) and not _has_real_pytest_evidence(evidence_block):
                missing.append(
                    "`wave_gate_check` cited in Evidence but no pytest/--runxfail output — "
                    "wave_gate_check reads an inventory string, not a test execution; "
                    "not GO-grade evidence"
                )

        # Commit SHA: H1 backtick form OR a `logs/` reference anywhere in body.
        if not _SHA_H1_RE.search(body) and not _LOGS_REF_RE.search(body):
            missing.append("missing commit SHA (expected in H1 as `commit \\`<sha>\\``) or `logs/` artifact ref")

        for field in missing:
            violations.append(f"{name}: {field}")

    return violations


def _scan_dir(directory: pathlib.Path) -> list[tuple[str, str]]:
    """Read all *-verification-report.md files from `directory`.

    Returns (filename, body) pairs. Non-existent directory → empty list (exit 0).
    """
    if not directory.exists():
        return []
    pairs: list[tuple[str, str]] = []
    for path in sorted(directory.glob("*-verification-report.md")):
        try:
            body = path.read_text(encoding="utf-8", errors="replace")
        except OSError:  # pragma: no cover — defensive
            continue
        pairs.append((path.name, body))
    return pairs


def main() -> int:
    # CLI: optional directory argument.
    if len(sys.argv) > 2:
        print(f"usage: {sys.argv[0]} [<dir>]", file=sys.stderr)
        return 1
    scan_dir = pathlib.Path(sys.argv[1]) if len(sys.argv) == 2 else DEFAULT_MAILBOX

    named_reports = _scan_dir(scan_dir)
    if not named_reports:
        print("GO-SCHEMA CHECK — no verification-report events found (vacuous pass).")
        return 0

    violations = go_report_violations(named_reports)
    total_go = sum(
        1 for _, body in named_reports if _VERDICT_GO_RE.search(body)
    )
    if violations:
        print(
            f"GO-SCHEMA CHECK — FAIL: {len(violations)} violation(s) "
            f"in {total_go} GO report(s)\n"
        )
        for v in violations:
            print(f"  ! {v}")
        return 1

    if total_go:
        print(
            f"GO-SCHEMA CHECK — PASS: {total_go} GO report(s) carry complete evidence."
        )
    else:
        print(
            f"GO-SCHEMA CHECK — PASS: {len(named_reports)} verification-report(s) found, "
            "none are GO verdicts (NITS/FAIL not gated)."
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
